/**
 * Generates src/css/tokens.css from src/tokens/radius.ts and
 * src/themes/{light,dark}.ts. Run via `pnpm --filter @st-manager/theme
 * build` after changing either — never edit the generated CSS by hand.
 */
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { baseRadius } from "../src/tokens/radius";
import { fontFamily } from "../src/tokens/typography";
import { darkTheme } from "../src/themes/dark";
import { lightTheme } from "../src/themes/light";
import type { SemanticTheme } from "../src/themes/light";

function toKebabCase(key: string): string {
  return key.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function toDeclarations(theme: SemanticTheme): string {
  return Object.entries(theme)
    .map(([key, value]) => `  --${toKebabCase(key)}: ${value};`)
    .join("\n");
}

const radiusDeclarations = [
  `  --radius: ${baseRadius};`,
  `  --radius-sm: calc(var(--radius) - 4px);`,
  `  --radius-md: calc(var(--radius) - 2px);`,
  `  --radius-lg: var(--radius);`,
  `  --radius-xl: calc(var(--radius) + 4px);`,
].join("\n");

// Font family doesn't vary between light/dark, so it lives in :root only,
// alongside radius — never duplicated into .dark.
const fontDeclarations = [
  `  --font-sans: ${fontFamily.sans};`,
  `  --font-mono: ${fontFamily.mono};`,
].join("\n");

const css = `/**
 * AUTO-GENERATED by packages/theme/scripts/generate-css.ts — do not edit
 * by hand. Source of truth: src/tokens/*.ts and src/themes/*.ts.
 * Regenerate with \`pnpm --filter @st-manager/theme build\`.
 */

:root {
${toDeclarations(lightTheme)}
${radiusDeclarations}
${fontDeclarations}
}

.dark {
${toDeclarations(darkTheme)}
}
`;

const outputPath = resolve(dirname(fileURLToPath(import.meta.url)), "../src/css/tokens.css");
writeFileSync(outputPath, css, "utf8");

process.stdout.write(`[@st-manager/theme] generated ${outputPath}\n`);
